name: LiveAgent
url: https://changelog.liveagent.com
author: QualityUnit
email: support@liveagent.com
description: The LiveAgent development team pushes out new features, improvements and bug fixes several times per day. Take a look at our latest updates listed here.
homepage: https://www.liveagent.com
title: LiveAgent Changelog

owner:
  name: QualityUnit.com, All rights reserved

google_analytics: UA-56486-1
google_analytics_domain: qualityunit.com

# External services
posts_url: "/posts/"
posts_title: "POSTS"
product_url: "https://www.ladesk.com"
product_title: "PRODUCT"
company_url: "https://www.qualityunit.com"
company_title: "ABOUT US"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Sass
sass:
  sass_dir:         _sass
  style:            compressed

# Site settings
include: ['_posts','_posts/version-0','_posts/version-2','_postst/version-3','_posts/version-4']
permalink: /posts/:year/:month/:day/:title/
relative_permalinks: false

authors:
  aharsani:
    name: Andrej Harsani
    gravatar: bf118f0a3f400fdb9bc0b32d8cc498d6
  mbebjak:
    name: Michal Bebjak
    gravatar: fee1cc2a670a7c6b096f6dcaae2e9a08
  mjancovic:
    name: Milos Jancovic
    gravatar: 5a27642c058fcde0108296e004160764
  jperdochqu:
    name: Jan Perdoch
    gravatar: b5be30f78bb29d6c7d7b2b406f10145f
  vzeman:
    name: Viktor Zeman
    gravatar: b08cb3172230cfa398a2b83884c181cc
  opok:
    name: Ondrej Pok
    gravatar: 4b9fe6f325e7a9ed0b80e8dff6a00b43
  jurajsim:
    name: Juraj Simon
    gravatar: 9ac0c69ed358a92808e16c5dd536a422
  dmilonova:
    name: Danka Bebjakova
    gravatar: 04afa4ac34093631f49f0624bc113093
  dbebjakova:
    name: Danka Bebjakova
    gravatar: 04afa4ac34093631f49f0624bc113093
